# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predictor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'predictor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpredictor.proto\x12\tpredictor\"-\n\tDataPoint\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\"`\n\x11PredictionRequest\x12)\n\x0b\x64\x61ta_points\x18\x01 \x03(\x0b\x32\x14.predictor.DataPoint\x12 \n\x18\x66orecast_horizon_seconds\x18\x02 \x01(\x05\"0\n\x12PredictionResponse\x12\x1a\n\x12predicted_replicas\x18\x01 \x01(\x05\x32U\n\tPredictor\x12H\n\x07Predict\x12\x1c.predictor.PredictionRequest\x1a\x1d.predictor.PredictionResponse\"\x00\x42<Z:github.com/kust1q/predictive-hpa-operator/api/v1/predictorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predictor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/kust1q/predictive-hpa-operator/api/v1/predictor'
  _globals['_DATAPOINT']._serialized_start=30
  _globals['_DATAPOINT']._serialized_end=75
  _globals['_PREDICTIONREQUEST']._serialized_start=77
  _globals['_PREDICTIONREQUEST']._serialized_end=173
  _globals['_PREDICTIONRESPONSE']._serialized_start=175
  _globals['_PREDICTIONRESPONSE']._serialized_end=223
  _globals['_PREDICTOR']._serialized_start=225
  _globals['_PREDICTOR']._serialized_end=310
# @@protoc_insertion_point(module_scope)
