// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/predictor.proto

package predictor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_proto_predictor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_predictor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_proto_predictor_proto_rawDescGZIP(), []int{0}
}

func (x *DataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PredictionRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DataPoints             []*DataPoint           `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	ForecastHorizonSeconds int32                  `protobuf:"varint,2,opt,name=forecast_horizon_seconds,json=forecastHorizonSeconds,proto3" json:"forecast_horizon_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PredictionRequest) Reset() {
	*x = PredictionRequest{}
	mi := &file_proto_predictor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionRequest) ProtoMessage() {}

func (x *PredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_predictor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionRequest.ProtoReflect.Descriptor instead.
func (*PredictionRequest) Descriptor() ([]byte, []int) {
	return file_proto_predictor_proto_rawDescGZIP(), []int{1}
}

func (x *PredictionRequest) GetDataPoints() []*DataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *PredictionRequest) GetForecastHorizonSeconds() int32 {
	if x != nil {
		return x.ForecastHorizonSeconds
	}
	return 0
}

type PredictionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PredictedReplicas int32                  `protobuf:"varint,1,opt,name=predicted_replicas,json=predictedReplicas,proto3" json:"predicted_replicas,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PredictionResponse) Reset() {
	*x = PredictionResponse{}
	mi := &file_proto_predictor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResponse) ProtoMessage() {}

func (x *PredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_predictor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResponse.ProtoReflect.Descriptor instead.
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return file_proto_predictor_proto_rawDescGZIP(), []int{2}
}

func (x *PredictionResponse) GetPredictedReplicas() int32 {
	if x != nil {
		return x.PredictedReplicas
	}
	return 0
}

var File_proto_predictor_proto protoreflect.FileDescriptor

const file_proto_predictor_proto_rawDesc = "" +
	"\n" +
	"\x15proto/predictor.proto\x12\tpredictor\"?\n" +
	"\tDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x84\x01\n" +
	"\x11PredictionRequest\x125\n" +
	"\vdata_points\x18\x01 \x03(\v2\x14.predictor.DataPointR\n" +
	"dataPoints\x128\n" +
	"\x18forecast_horizon_seconds\x18\x02 \x01(\x05R\x16forecastHorizonSeconds\"C\n" +
	"\x12PredictionResponse\x12-\n" +
	"\x12predicted_replicas\x18\x01 \x01(\x05R\x11predictedReplicas2U\n" +
	"\tPredictor\x12H\n" +
	"\aPredict\x12\x1c.predictor.PredictionRequest\x1a\x1d.predictor.PredictionResponse\"\x00B<Z:github.com/kust1q/predictive-hpa-operator/api/v1/predictorb\x06proto3"

var (
	file_proto_predictor_proto_rawDescOnce sync.Once
	file_proto_predictor_proto_rawDescData []byte
)

func file_proto_predictor_proto_rawDescGZIP() []byte {
	file_proto_predictor_proto_rawDescOnce.Do(func() {
		file_proto_predictor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_predictor_proto_rawDesc), len(file_proto_predictor_proto_rawDesc)))
	})
	return file_proto_predictor_proto_rawDescData
}

var file_proto_predictor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_predictor_proto_goTypes = []any{
	(*DataPoint)(nil),          // 0: predictor.DataPoint
	(*PredictionRequest)(nil),  // 1: predictor.PredictionRequest
	(*PredictionResponse)(nil), // 2: predictor.PredictionResponse
}
var file_proto_predictor_proto_depIdxs = []int32{
	0, // 0: predictor.PredictionRequest.data_points:type_name -> predictor.DataPoint
	1, // 1: predictor.Predictor.Predict:input_type -> predictor.PredictionRequest
	2, // 2: predictor.Predictor.Predict:output_type -> predictor.PredictionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_predictor_proto_init() }
func file_proto_predictor_proto_init() {
	if File_proto_predictor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_predictor_proto_rawDesc), len(file_proto_predictor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_predictor_proto_goTypes,
		DependencyIndexes: file_proto_predictor_proto_depIdxs,
		MessageInfos:      file_proto_predictor_proto_msgTypes,
	}.Build()
	File_proto_predictor_proto = out.File
	file_proto_predictor_proto_goTypes = nil
	file_proto_predictor_proto_depIdxs = nil
}
